<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <GeneratedCodeDir>$(MSBuildProjectDirectory)\Generated</GeneratedCodeDir>
    <CodeGenSamplesFile>$(MSBuildProjectDirectory)\..\..\packages\com.celeriedaway.zergrush\Samples~\CodeGenBasics\CodeGenSamples.cs</CodeGenSamplesFile>
    <DictionarySamplesFile>$(MSBuildProjectDirectory)\DictionaryUpdateFromSample.cs</DictionarySamplesFile>
    <UnityStubsFile>$(MSBuildProjectDirectory)\UnityEngineStubs.cs</UnityStubsFile>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(GeneratedCodeDir)\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ZergRush.CodeGen\ZergRush.CodeGen.csproj" />
    <ProjectReference Include="..\..\src\ZergRush.CodeGen.Cli\ZergRush.CodeGen.Cli.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="$(CodeGenSamplesFile)" Link="Samples\CodeGenSamples.cs" />
  </ItemGroup>

  <Target Name="GenerateCodeGenSamples" BeforeTargets="CoreCompile" DependsOnTargets="ResolveProjectReferences">
    <RemoveDir Directories="$(GeneratedCodeDir)" />
    <MakeDir Directories="$(GeneratedCodeDir)" />
    <Exec Command="dotnet &quot;$(MSBuildProjectDirectory)\..\..\src\ZergRush.CodeGen.Cli\bin\$(Configuration)\net10.0\ZergRush.CodeGen.Cli.dll&quot; --generate &quot;$(GeneratedCodeDir)&quot; &quot;$(CodeGenSamplesFile)&quot; &quot;$(DictionarySamplesFile)&quot; &quot;$(UnityStubsFile)&quot;" />
    <ItemGroup>
      <Compile Include="$(GeneratedCodeDir)\**\*.cs" />
    </ItemGroup>
  </Target>

</Project>
